### ISSUE TITLE
reasonReference benötigt?

### ISSUE THREAD

**Issue by lucscherer** [medizininformatik-initiative/kerndatensatz-bildgebung#14]
Aktuell in der ImagingStudy im UML und ArtDecor angegeben aber ohne zugehörige Referenzkante im UML hinterlegt. Bitte am Montag nochmla drüber diskutieren ob für erstes Modell benötigt

**Comment by noemide** [comment]
Indikation und Bildgebungsgrund zusammenführen? soll bleiben und im UML wie andere Referenzen "ausformuliert" werden. @alexa-ian Was denkst Du?

**Comment by alexa-ian** [comment]
Mit https://github.com/medizininformatik-initiative/kerndatensatz-bildgebung/commit/d9835d894f71bd49a931f5bebdaa61f9c2500973 ist reasonCode aus der ImagingStudy rausgeflogen.
