### ISSUE TITLE
Implikationen von erlaubtem Specimen im Diagnostic Report durchdenken

### ISSUE THREAD

**Issue by noemide** [medizininformatik-initiative/kerndatensatz-bildgebung#19]
In GOLD war es noch verboten. Was bedeutet das für alle anderen Observations, diese können dann auch Specimen Bezug 
haben?

- [ ] Patho Umsetzung sichten
- [ ] Mikrobio Umsetzung sichten

Vermutlich erst etwas für die zweite Version.

**Comment by lucscherer** [comment]
Wird für den 2. Release nochmal angestoßen
