### ISSUE TITLE
Referenz auf Kontrastmittelgabe

### ISSUE THREAD

**Issue by dmaennle** [medizininformatik-initiative/kerndatensatz-bildgebung#2]
Neuer Task:
Kontrastmittelgabe über MedicationAdministration mappen: https://hl7.org/fhir/medicationadministration.html
In ImageingStudy nur Referenz auf MedicationAdministration anlegen

**Comment by alexa-ian** [comment]
In der ImagingStudy wird die Kontrastmittelgabe auf MedicationStatement referenziert 👍
