### ISSUE TITLE
SNOMED CT Version in Value Sets

### ISSUE THREAD

**Issue by lucscherer** [medizininformatik-initiative/kerndatensatz-bildgebung#30]

**Comment by alexa-ian** [comment]
Ist dieses Issue [hiermit](https://github.com/medizininformatik-initiative/kerndatensatz-bildgebung/issues/31) hinfällig?

**Comment by violaBe** [comment]
Ich hatte das issue so verstanden, dass für das ValueSet eine version definiert werden soll. 
![image](https://github.com/user-attachments/assets/744f97ff-02de-4f6e-9829-ea4116a9b6ea)
https://hl7.org/fhir/R4/shareablevalueset-definitions.html#ValueSet.version

Diesen Kommentar interpretiere ich eher, dass für einzelne SNOMED codes angegeben werden soll, welche snomed ct version also z.B. https://browser.ihtsdotools.org/ 2024-05-15. 
![image](https://github.com/user-attachments/assets/8c7cf7bd-06af-4a6e-a4a0-32fe934a8ddd)

**Comment by lucscherer** [comment]
Verbleibt erstmal ohne Version, da im JSON die Version nicht mehr sichtbar ist. Muss wenn dann nachträglich in das JSON eingetragen werden

**Comment by lucscherer** [comment]
Version wurde ergänzt und auf 2024-07-01 in Absprache mit dem Ontoserver festgelegt
