### ISSUE TITLE
ValueSets ergänzen

### ISSUE THREAD

**Issue by alexa-ian** [medizininformatik-initiative/kerndatensatz-bildgebung#31]
Unsere 4 ValueSets sollten um die Werte ergänzt werden, die in [ShareableValueSet](https://hl7.org/fhir/R4/shareablevalueset.html) enthalten sind, also:

- version
- experimental
- publisher

**Comment by violaBe** [comment]
Eigentlich gute Idee. Aber wie befüllen wir das? Gibt es Beispiele wie es in anderen Modulen gehandhabt wird? 

- version dann gleich setzen mit der Modul-version? 
- experimental: "A Boolean value to indicate that this value set is authored for testing purposes (or education/evaluation/marketing) and is not intended to be used for genuine usage."   
Binding, keine Pflichtvorgabe  
Manches kommt von GOLD, oder? Aber wir können nicht garantieren, dass alles 100% passt? 
experimental= true hört sich aber auch nicht gut an, wenn wir die Daten in unsere Prod Server laden. 
- publisher = KDS Team ?

**Comment by lucscherer** [comment]
Das habe ich während der Kommentierung schon weitestgehend umgesetz

**Comment by lucscherer** [comment]
Waren noch Überbleibsel aus der GOLD Entwicklung die ich vor dem Release nicht bemerkt haben

**Comment by alexa-ian** [comment]
Stimmt, ist schon umgesetzt. Wird geschlossen.
