### ISSUE TITLE
ServiceRequest code

### ISSUE THREAD

**Issue by alexa-ian** [medizininformatik-initiative/kerndatensatz-bildgebung#33]
Sollte ServiceRequest.code nicht ggf. 1..1 sein, statt wie im Basisprofile 0..1? Durch die Bandbreite an bereitgestellten Slices sollte doch hoffentlich etwas dabei sein; durch das offene Slicing ist ja sogar die Verwendung eines Hauscodes erlaubt.

**Comment by violaBe** [comment]
Diskussion am 14.10.   
Use case? Annahme: nicht über code sondern über category wird nach SR gesucht  

Diskussion: Anforderungsdokumentation heterogen und nicht unbedingt digital  

Ggf. Must Support setzen als Zwischenlösung? Dann als snomed angeben , suchparameter angeben – dann können die, die so weit sind es befüllen

**Comment by alexa-ian** [comment]
Bitte dann auch das dazugehörige Ticket dokumentieren und schließen: https://hl7germany.atlassian.net/browse/HDB-508

**Comment by lucscherer** [comment]
@noemide
