### ISSUE TITLE
Vereinheitlichung SNOMED-CT FSN und PT

### ISSUE THREAD

**Issue by alexa-ian** [medizininformatik-initiative/kerndatensatz-bildgebung#35]
Es wird teilweise unheitlich mit SNOMED CT-Displays gearbeitet: im Profil MII_PR_Bildgebung_Radiologischer_Befund ist folgende Regel mit dem Preferred Term:

* category.coding[snomed-ct] = $SCT#4201000179104 "Imaging report"

während im Profil MII_PR_Bildgebung_Bildgebungsprozedur folgende Regel mit dem Fully Specified Name angegeben ist:

* category.coding[sct] ^patternCodeableConcept = $SCT#363679005 "Imaging (procedure)"

Das sollte zumindest modul-intern vereinheitlicht werden, aber auch die Rücksprache mit den weiteren KDS-Teams gehalten werden, was hier angebracht ist.

**Comment by noemide** [comment]
Vorschlag: Displays komplett weglassen.

**Comment by lucscherer** [comment]
In den Profilen weglassen, in den Beispielen mit Display am besten mit Fully Specified Name zur besseren Übersichtlichkeit.

**Comment by lucscherer** [comment]
Kommentar wurde eingearbeitet wie oben beschrieben
