### ISSUE TITLE
BodyStructure: Bindings

### ISSUE THREAD

**Issue by alexa-ian** [medizininformatik-initiative/kerndatensatz-bildgebung#37]
Im Profil MII_PR_Bildgebung_Koerperstruktur wurden keine Bindings für morphology, location und locationQualifier konkretisiert. Im Basisprofil ist hier jeweils ein Example-Binding an ein (schon ganz gut passendes) SNOMED CT ValueSet. Dies sollte innerhalb des Profils aber konkretisiert werden, ob nun mit einem eigenen ValueSet, oder durch ein Überschreiben der Binding-Strength auf preferred oder sogar preferred. Eine Auswertbarkeit ist sonst gar nicht gegeben!

**Comment by lucscherer** [comment]
Binding-strength wurde mit preferred überschrieben
