### ISSUE TITLE
DICOM-URL (Enum)-Problematik auflösen

### ISSUE THREAD

**Issue by alexa-ian** [medizininformatik-initiative/kerndatensatz-bildgebung#38]
Idee für fehlende VS (z.B. Scanning Sequence):

CodeSystem für die Enum definieren (innerhalb von https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem z.B.) und dann ein VS definieren, das die Codes enthält, die wir brauchen.

Die URL des CS müssten die Implementierenden dann halt hart codieren, aber ansonsten funktioniert alles

**Comment by alexa-ian** [comment]
Bitte dann auch (wenn möglich) das zugehörige Ticket dokumentieren und schließen: https://hl7germany.atlassian.net/browse/HDB-503

**Comment by lucscherer** [comment]
ImageType ist Hierachisch angelegt. 
Hier unterteilt in:

1. Pixel Data Characteristics
2. Patient Examination Characteristics
3. Modality Specific Characteristics
4. Implemantation Specific Identifiers

Modality muss ebenfalls in die einzelnen Aufgeteilt werden, da jede ihre eigenen Attribute hat.

- https://dicom.innolitics.com/ciods/ct-image/general-image/00080008
- https://dicom.innolitics.com/ciods/ct-image/ct-image/00080008
- https://dicom.innolitics.com/ciods/mr-image/mr-image/00080008
- https://dicom.innolitics.com/ciods/nuclear-medicine-image/nm-image/00080008
- https://dicom.innolitics.com/ciods/ultrasound-image/us-image/00080008
- https://dicom.innolitics.com/ciods/x-ray-angiographic-image/x-ray-image/00080008

**Comment by lucscherer** [comment]
Die offenen Tasks sind bei uns aktuell noch nicht in der Modalität umgesetzt und werden deshalb nicht betrachtet.
Für CR gibt es keinen CR spezifischen Imagetype, deshlab nicht im Codessystem erwähnt.
Für PT, DX und MG werden die Values 3 und 4 nicht weiter spezifiziert und besitzen einen Länge 0

**Comment by lucscherer** [comment]
@noemide
