### ISSUE TITLE
Extension Instanz-Details

### ISSUE THREAD

**Issue by alexa-ian** [medizininformatik-initiative/kerndatensatz-bildgebung#39]
Hier wäre unter extension[imageType].value[x] eventuell zusätzlich zum String-Datentyp ein Binding denkbar. Wenn ich weiterhin in das Example mii-exa-bildgebung-bildgebungsstudie-cr schaue, sind dort mehrere imageType angegeben, aber imageType ist 0..1:

{
  "extension": [
    {
      "url": "imageType",
      "valueString": "[ORIGINAL,PRIMARY,RAD]"
    }
  ],
  "url": "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-instanz-details"
}

**Comment by violaBe** [comment]
Freitext von FDPG sowieso nicht auswertbar

**Comment by alexa-ian** [comment]
wird durch #38 mitgelöst

**Comment by lucscherer** [comment]
Lösung wurde präsentiert in #38

**Comment by lucscherer** [comment]
@noemide
