### ISSUE TITLE
Kardinalität der UID (Serie) anpassen

### ISSUE THREAD

**Issue by AMB-Git-Hub** [medizininformatik-initiative/kerndatensatz-bildgebung#4]
UID auf Serienebene soll nicht notwendig sein. 
Somit ist hier die Kardinalität anzupassen auf 0..1

Entspricht diesem Item, hier wurde die Kardinalität allerdings nicht angegeben

https://develop.art-decor.org/ad/#/strainad-/datasets/dataset/2.16.840.1.113883.3.1937.99.61.74.1.8/2023-09-13T11:59:28/concept/2.16.840.1.113883.3.1937.99.61.74.2.1.263/2023-09-13T12:24:33

**Comment by alexa-ian** [comment]
@mematt Was sagst Du?

**Comment by mematt** [comment]
Es ist verpflichtend und bei uns auch immer vorhanden.
