### ISSUE TITLE
changes requested by clinicians

### ISSUE THREAD

**Issue by alexa-ian** [medizininformatik-initiative/kerndatensatz-bildgebung#44]
- Study - Series: 1..1 - 0..*
- Series - Instance: 1..1 - 0..*
- sliceThickness: 0..1 (not suitable for every modaity)
- more MR/MG parameters? --> echo time, repetition time, flip angle, inversion time, projection, filter

**Comment by alexa-ian** [comment]
sliceThickness haben wir wohl schon geändert :)

**Comment by lucscherer** [comment]
Wie sieht die Datenlage zu den weiteren MR Tags aus?

**Comment by alexa-ian** [comment]
Gut. Man könnte die o.g. größtenteils mit abbilden - also TE, TR, flip angle, inversion time ist immer da bei MRs

Step 1-3 sind auch schon erledigt ✔️

**Comment by alexa-ian** [comment]
Alles bis auf "Filter" umgesetzt, da FIlter ein Freitext-Feld ist. Siehe https://github.com/medizininformatik-initiative/kerndatensatz-bildgebung/pull/58
