### ISSUE TITLE
Medication (KM) geradeziehen

### ISSUE THREAD

**Issue by alexa-ian** [medizininformatik-initiative/kerndatensatz-bildgebung#53]
- Kardinalität MA.partOf anpassen und im Profil ergänzen
- beide möglichen Referenzen (MA + MS) in Serie ergänzen

**Comment by lucscherer** [comment]
Referenzen hinzugefügt

UML Bild muss noch erstellt werden

**Comment by lucscherer** [comment]
neues UML Bild wurde erstellt
