### ISSUE TITLE
Diskussion: Observations statt Extensions verwenden?

### ISSUE THREAD

**Issue by alexa-ian** [medizininformatik-initiative/kerndatensatz-bildgebung#6]
Man könnte evtl. die hinzuzufügenden Attribute auf Studien-Ebene über Observations lösen (siehe Modul Intensivmedizin --> Geräteparameter).

**Comment by SchmitzDan** [comment]
Finde ich persönlich immer die bessere Variante, da man sich damit im Standard bewegt. Wenn man Extensions vermeiden kann, sollte man sie auch vermeiden.
